# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheat_entry', '0002_auto_20170518_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheatapplication',
            name='class_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cheatapplication',
            name='num_q',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cheatapplication',
            name='subject',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
